spring.application.name=SecureAssess

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/secureassess
spring.datasource.username=root
spring.datasource.password=Saiteja@2023

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true